# Generated by Django 5.0.7 on 2024-08-01 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('rollnumber', models.AutoField(primary_key=True, serialize=False)),
                ('pfp', models.ImageField(upload_to='images/')),
                ('fullname', models.CharField(default=None, max_length=400)),
                ('dob', models.DateField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mobile_number', models.IntegerField()),
                ('gender', models.CharField(max_length=200)),
                ('fathername', models.TextField()),
                ('address', models.TextField()),
                ('class10_details', models.JSONField()),
                ('class12_details', models.JSONField()),
                ('graduation_details', models.JSONField()),
                ('masters_details', models.JSONField()),
                ('courses_applied', models.JSONField()),
                ('enrollment_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.IntegerField()),
                ('fee_amount', models.IntegerField()),
                ('deposit_date', models.DateField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstpage.student')),
            ],
        ),
    ]
