# Generated by Django 5.0.7 on 2024-08-03 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstpage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pfp', models.ImageField(upload_to='images/')),
                ('fullname', models.CharField(default=None, max_length=400)),
                ('dob', models.DateField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mobile_number', models.IntegerField()),
                ('gender', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('class10_details', models.JSONField()),
                ('class12_details', models.JSONField()),
                ('graduation_details', models.JSONField()),
                ('masters_details', models.JSONField()),
                ('joining_date', models.DateField()),
            ],
        ),
    ]
