# Generated by Django 5.0.7 on 2024-08-13 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstpage', '0004_newupdate_alter_fee_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newupdate',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
